name: Create comment on new issues

on:
  issues:
    types: [opened]
  workflow_dispatch:
  
jobs:
  comment-with-actions:
    runs-on: windows-latest
    steps:
      - name: dump github context
        run: echo '${{ toJSON(github.event) }} | jq '
        shell: bash
